name: Run checks on incoming PR

on:
  pull_request:
    branches: [master, release, develop]

  # allow running this workflow manually
  workflow_dispatch:

jobs:
  windows-build-check:
    runs-on: windows-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build android project
        uses: igotinfected-ci/build-monogame@v2
        with:
          solution-path: '${{ github.workspace }}\EternalFrost.sln'
          content-mgcb-path: '${{ github.workspace }}\ProjEternalFrostect\EternalFrost\Content'
          content-mgcb-platform: "Windows"
          csproj-path: '${{ github.workspace }}\EternalFrost\EternalFrost.csproj'
          build-target: "PackageForWindows"
          build-configuration: "Release"
